use chromiumoxid::cdp::browser_protocol::network::EventRequestWillBeSent;
use chromiumoxid::cdp::CdpEventMessage;
use chromiumoxid_types::Message;
use serde::de::{self, Deserializer, MapAccess, Visitor};
fn main() {
    let params = r###"{"requestId":"30609.72","loaderId":"7B1C95B6135A0EBE8244D8AF49D36CFE","documentURL":"https://en.wikipedia.org/wiki/Main_Page",
    "request":{"url":"url","method":"POST","headers":{"sec-ch-ua":"\";Not\\\\A\\\"Brand\";v=\"99\", \"Chromium\";v=\"88\"","Referer":"h","sec-ch-ua-mobile":"","User-Agent":"","Content-Type":"text/plain;charset=UTF-8"},"hasPostData":true,"postDataEntries":[{"bytes":""}],"mixedContentType":"none","initialPriority":"Low","referrerPolicy":"origin-when-cross-origin"},"timestamp":443084.659917,"wallTime":1607378805.20023,"initiator":{"type":"script","stack":{"callFrames":[{"functionName":"sendBeacon","scriptId":"10","url":"","lineNumber":15,"columnNumber":311},{"functionName":"reallyRecordImpression","scriptId":"10","url":"","lineNumber":15,"columnNumber":54},{"functionName":"recordImpression","scriptId":"10","url":"","lineNumber":14,"columnNumber":495},{"functionName":"processAfterBannerFetch","scriptId":"10","url":"","lineNumber":18,"columnNumber":98},{"functionName":"reallyInsertBanner","scriptId":"10","url":"","lineNumber":18,"columnNumber":856},{"functionName":"","scriptId":"10","url":"","lineNumber":20,"columnNumber":287},{"functionName":"mightThrow","scriptId":"11","url":"https://en.wikipedia.org/w/load.php?lang=en&modules=ext.centralNotice.choiceData%7Cjquery&skin=vector&version=1ingw","lineNumber":63,"columnNumber":148},{"functionName":"process","scriptId":"11","url":"https://en.wikipedia.org/w/load.php?lang=en&modules=ext.centralNotice.choiceData%7Cjquery&skin=vector&version=1ingw","lineNumber":63,"columnNumber":807}]}},"type":"Other","frameId":"F69420D58A65470EDEC7FABBF0BC6D65","hasUserGesture":false}"###;
    let req = serde_json::from_str::<EventRequestWillBeSent>(params).unwrap();

    println!("finished EventRequestWillBeSent");

    let s = r###"{"method":"Network.requestWillBeSent","params":{"requestId":"30609.72","loaderId":"7B1C95B6135A0EBE8244D8AF49D36CFE","documentURL":"https://en.wikipedia.org/wiki/Main_Page","request":{"url":"https://en.wikipedia.org/beacon/impression?country=DE&region=BE&anonymous=true&project=wikipedia&db=enwiki&uselang=en&device=desktop&debug=false&randomcampaign=0.2414334597222616&randombanner=0.2952188600409704&recordImpressionSampleRate=1&impressionEventSampleRate=0.01&campaignStatuses=%5B%7B%22statusCode%22%3A%226%22%2C%22campaign%22%3A%22C20_WMDE_EN_Test_04%22%2C%22bannersCount%22%3A2%7D%5D&status=banner_shown&statusCode=6&campaign=C20_WMDE_EN_Test_04&campaignCategory=fundraising&campaignCategoryUsesLegacy=true&bucket=1&bannersNotGuaranteedToDisplay=true&banner=B20_WMDE_EN_Test_04_var&bannerCategory=fundraising&alterFunctionMissing=true&result=show","method":"POST","headers":{"sec-ch-ua":"\";Not\\\\A\\\"Brand\";v=\"99\", \"Chromium\";v=\"88\"","Referer":"https://en.wikipedia.org/wiki/Main_Page","sec-ch-ua-mobile":"?0","User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4320.0 Safari/537.36","Content-Type":"text/plain;charset=UTF-8"},"hasPostData":true,"postDataEntries":[{"bytes":""}],"mixedContentType":"none","initialPriority":"Low","referrerPolicy":"origin-when-cross-origin"},"timestamp":443084.659917,"wallTime":1607378805.20023,"initiator":{"type":"script","stack":{"callFrames":[{"functionName":"sendBeacon","scriptId":"10","url":"","lineNumber":15,"columnNumber":311},{"functionName":"reallyRecordImpression","scriptId":"10","url":"","lineNumber":15,"columnNumber":54},{"functionName":"recordImpression","scriptId":"10","url":"","lineNumber":14,"columnNumber":495},{"functionName":"processAfterBannerFetch","scriptId":"10","url":"","lineNumber":18,"columnNumber":98},{"functionName":"reallyInsertBanner","scriptId":"10","url":"","lineNumber":18,"columnNumber":856},{"functionName":"","scriptId":"10","url":"","lineNumber":20,"columnNumber":287},{"functionName":"mightThrow","scriptId":"11","url":"https://en.wikipedia.org/w/load.php?lang=en&modules=ext.centralNotice.choiceData%7Cjquery&skin=vector&version=1ingw","lineNumber":63,"columnNumber":148},{"functionName":"process","scriptId":"11","url":"https://en.wikipedia.org/w/load.php?lang=en&modules=ext.centralNotice.choiceData%7Cjquery&skin=vector&version=1ingw","lineNumber":63,"columnNumber":807}]}},"type":"Other","frameId":"F69420D58A65470EDEC7FABBF0BC6D65","hasUserGesture":false},"sessionId":"EB6C1F600F1E113CB49E057AEBF52DAE"}"###;
    let req = serde_json::from_str::<Message<CdpEventMessage>>(s).unwrap();
}
